# Uncomment the next line to define a global platform for your project
# platform :ios, '12.0'

target 'Hotspot' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Hotspot
  pod 'DeviceKit', '~> 1.3'
  pod 'EasyPeasy'
  pod 'lottie-ios'
  pod 'Then'
end
